#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Musical Studio · sync-env
#
# .env/secrets.env (마스터, SSoT) → .env.local (Next.js 자동 로드)
#
# 정책:
#   - secrets.env가 source of truth.
#   - .env.local은 항상 secrets.env에서 생성 (덮어쓰기).
#   - secrets.env의 DEV_ACCESS_TOKEN/NEXTAUTH_SECRET이 비어있으면:
#     자동 생성 후 secrets.env에 다시 기록 (다음 sync부터 보존).
#   - 이렇게 하면 owner의 secrets.env를 partner가 SCP로 받았을 때
#     양쪽 토큰이 자동 동일 → dev server 인증 호환.
#
# 사용법: bash scripts/sync-env.sh
# ═══════════════════════════════════════════════════════════════════
set -e

SRC=".env/secrets.env"
DEST=".env.local"

if [ ! -f "$SRC" ]; then
  echo "[FAIL] $SRC not found. .env/ 디렉토리에 secrets.env 작성 필요."
  exit 1
fi

# ─── 1) secrets.env의 토큰이 비어있으면 채워서 secrets.env에 다시 기록 ──
fill_token_in_master() {
  local key="$1"
  local generator="$2"   # bash command
  local current
  current=$(grep -E "^${key}=" "$SRC" | head -1 | cut -d= -f2-)
  if [ -z "$current" ]; then
    local new_val
    new_val=$(eval "$generator")
    if grep -qE "^${key}=" "$SRC"; then
      # 기존 빈 라인 교체 (BSD/GNU sed 호환)
      sed -i.bak "s|^${key}=.*|${key}=${new_val}|" "$SRC" && rm -f "${SRC}.bak"
    else
      echo "${key}=${new_val}" >> "$SRC"
    fi
    echo "[sync-env] ${key} 자동 생성 → secrets.env에 저장됨"
  fi
}

fill_token_in_master "NEXTAUTH_SECRET" "openssl rand -base64 32"
fill_token_in_master "DEV_ACCESS_TOKEN" "openssl rand -hex 32"

# ─── 2) secrets.env → .env.local 덮어쓰기 ──────────────────────────
{
  echo "# Auto-generated by scripts/sync-env.sh — DO NOT EDIT DIRECTLY"
  echo "# 모든 값은 .env/secrets.env (SSoT) 에서 가져옴."
  echo "# 값 바꾸려면 secrets.env 수정 후 이 스크립트 재실행."
  echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""
  grep -E "^(NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_JWT_SECRET|SUPABASE_DB_PASSWORD|SUPABASE_PROJECT_REF|DATABASE_URL|GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|GOOGLE_OAUTH_JSON_PATH|NEXT_PUBLIC_APP_URL|HOST_LAN_IP|HOST_PUBLIC_IP|DEV_PORT|SUPABASE_API_PORT|DDNS_HOSTNAME|DDNS_PROVIDER|GITHUB_REPO_OWNER|GITHUB_REPO_NAME|PARTNER_GITHUB_USERNAME|NEXTAUTH_SECRET|DEV_ACCESS_TOKEN)=" "$SRC"
} > "$DEST"

chmod 600 "$DEST"

LINES=$(wc -l < "$DEST")
SIZE=$(stat -c %s "$DEST")
echo "[OK] $DEST: $LINES lines, $SIZE bytes"

if git check-ignore "$DEST" > /dev/null 2>&1; then
  echo "[OK] $DEST is gitignored"
else
  echo "[WARN] $DEST is NOT gitignored — .gitignore 확인 필요"
fi

if git check-ignore "$SRC" > /dev/null 2>&1; then
  echo "[OK] $SRC is gitignored"
else
  echo "[WARN] $SRC is NOT gitignored"
fi
