#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Musical Studio · sync-env
#
# .env/secrets.env (마스터) → .env.local (Next.js 자동 로드)
# 매번 secrets.env 변경 후 실행. idempotent.
#
# 사용법:
#   bash scripts/sync-env.sh
#
# Next.js 자동 로드 우선순위:
#   .env.local > .env.development.local > .env.development > .env
# ═══════════════════════════════════════════════════════════════════
set -e

SRC=".env/secrets.env"
DEST=".env.local"

if [ ! -f "$SRC" ]; then
  echo "[FAIL] $SRC not found. .env/ 디렉토리에 secrets.env 작성 필요."
  exit 1
fi

# Preserve existing auto-generated tokens if present
EXISTING_NEXTAUTH_SECRET=""
EXISTING_DEV_TOKEN=""
if [ -f "$DEST" ]; then
  EXISTING_NEXTAUTH_SECRET=$(grep -E "^NEXTAUTH_SECRET=" "$DEST" | cut -d= -f2- || true)
  EXISTING_DEV_TOKEN=$(grep -E "^DEV_ACCESS_TOKEN=" "$DEST" | cut -d= -f2- || true)
fi

# Generate fresh if missing
NEXTAUTH_SECRET=${EXISTING_NEXTAUTH_SECRET:-$(openssl rand -base64 32)}
DEV_ACCESS_TOKEN=${EXISTING_DEV_TOKEN:-$(openssl rand -hex 16)}

{
  echo "# Auto-generated by scripts/sync-env.sh — DO NOT EDIT DIRECTLY"
  echo "# 변경할 값이 있으면 .env/secrets.env 수정 후 이 스크립트 재실행"
  echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""
  # Pass-through keys from secrets.env
  grep -E "^(NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_JWT_SECRET|SUPABASE_DB_PASSWORD|SUPABASE_PROJECT_REF|DATABASE_URL|GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|GOOGLE_OAUTH_JSON_PATH|NEXT_PUBLIC_APP_URL|HOST_LAN_IP|HOST_PUBLIC_IP|DEV_PORT|SUPABASE_API_PORT|DDNS_HOSTNAME|DDNS_PROVIDER|GITHUB_REPO_OWNER|GITHUB_REPO_NAME|PARTNER_GITHUB_USERNAME)=" "$SRC"
  echo ""
  echo "# Auto-generated tokens (보존됨 — 회전 시 .env.local 삭제 후 재실행)"
  echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
  echo "DEV_ACCESS_TOKEN=$DEV_ACCESS_TOKEN"
} > "$DEST"

chmod 600 "$DEST"

# Verify
LINES=$(wc -l < "$DEST")
SIZE=$(stat -c %s "$DEST")
echo "[OK] $DEST: $LINES lines, $SIZE bytes"

# Verify gitignored
if git check-ignore "$DEST" > /dev/null 2>&1; then
  echo "[OK] $DEST is gitignored"
else
  echo "[WARN] $DEST is NOT gitignored — .gitignore 확인 필요"
fi
